### ISSUE TITLE
Compass crashes application on rotation from portrait to landscape.

### ISSUE THREAD

**Issue by jaybowman** [Esri/arcgis-runtime-toolkit-android#119]
I have the compass initialized after I setup my mapView. when I rotate the device from portrait to landscape I get the error below.

I'm using 100.6.0 SDK

  mMapView.setMap(new ArcGISMap(map));
  mCompass = new Compass(mMapView.getContext());  
  mCompass.setAutoHide(false);
  mCompass.addToGeoView(mMapView);

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.thevillages.myfirstapp, PID: 28447
    com.esri.arcgisruntime.ArcGISRuntimeException: Invalid argument: Null value.
        at com.esri.arcgisruntime.internal.jni.CoreMapView.nativeGetRotation(Native Method)
        at com.esri.arcgisruntime.internal.jni.CoreMapView.s(SourceFile:224)
        at com.esri.arcgisruntime.internal.h.b.o.p(SourceFile:236)
        at com.esri.arcgisruntime.mapping.view.MapView.getMapRotation(SourceFile:317)
        at com.esri.arcgisruntime.toolkit.compass.Compass$viewpointChangedListener$1.viewpointChanged(Compass.kt:136)
        at com.esri.arcgisruntime.internal.h.b.af$1.run(SourceFile:51)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by LDuncAndroid** [comment]
Hi Jay, thank you for raising this.

I am having trouble reproducing the crash, using the following code:

```
class ToolkitActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_toolkit)

        val map = ArcGISMap(Basemap.createImagery())
        mapView.map = map

        val compass = Compass(mapView.context)
        compass.isAutoHide = false
        compass.addToGeoView(mapView)
    }
}
```

I notice that you are calling: `mCompass.setAutoHide(false);` but this method has been changed to `mCompass.setAutoHide(false);` in the `100.5.0` release which has been merged into master. Are you potentially using an older version of the Toolkit?

Thanks,

Luke

**Comment by jaybowman** [comment]
I just did a clone of the repo yesterday. My map app is using arcgisruntime 100.6.0 . I trying to use your new navigation classes. We have our own map servers. Here is my complete map setup code.
I get the same error with both of your workflows for instantiating the compass.

I updated the tools project’s versions.gradle file to use 100.6.0 and rebuild the aar file, thinking that this might fix the error. But I still get the same error.


//set up mapview
mMapView = findViewById(R.id.mapNavView1);
String  mapService = "https://arc5.thevillages.com/arcgis/rest/services/PUBLICMAP26/MapServer/";
ArcGISTiledLayer layer = new ArcGISTiledLayer(mapService);
Basemap map = new Basemap(layer);
mMapView.setMap(new ArcGISMap(map));

mGraphicsOverlay = new  GraphicsOverlay();
mMapView.getGraphicsOverlays().add(mGraphicsOverlay);

mCompass = findViewById(R.id.compass); // new Compass(mMapView.getContext());
mCompass.bindTo(mMapView);;




Jay Bowman
Software Engineer | The Villages® Technology Solutions Group<http://www.thevillagestsg.com/>
Direct: 352.674.1528 | Support: 352.674.1530

**Comment by LDuncAndroid** [comment]
> I just did a clone of the repo yesterday. My map app is using arcgisruntime 100.6.0 . I trying to use your new navigation classes. We have our own map servers. Here is my complete map setup code. I get the same error with both of your workflows for instantiating the compass. I updated the tools project’s versions.gradle file to use 100.6.0 and rebuild the aar file, thinking that this might fix the error. But I still get the same error. ```java //set up mapview mMapView = findViewById(R.id.mapNavView1); String mapService = "https://arc5.thevillages.com/arcgis/rest/services/PUBLICMAP26/MapServer/"; ArcGISTiledLayer layer = new ArcGISTiledLayer(mapService); Basemap map = new Basemap(layer); mMapView.setMap(new ArcGISMap(map)); mGraphicsOverlay = new GraphicsOverlay(); mMapView.getGraphicsOverlays().add(mGraphicsOverlay); mCompass = findViewById(R.id.compass); // new Compass(mMapView.getContext()); mCompass.bindTo(mMapView);; ```

Hi @jaybowman sorry for not responding sooner.

I've tried using your code and still cannot replicate this issue.

Are you able to zip the entire app and forward to me at lduncan@esri.com and we can try to resolve this?

Thanks,

Luke
